version: '3.7'

networks:
  kafka-spark:
    driver: bridge
    ipam:
      driver: default
      config: 
        - subnet: 172.28.0.0/24
          gateway: 172.28.0.1

services:
  # --------- Kafka Services ---------
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    restart: unless-stopped
    networks:
      kafka-spark:
        ipv4_address: 172.28.0.5
  
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_CREATE_TOPICS: "wikistream"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    networks:
      kafka-spark:
        ipv4_address: 172.28.0.6
    depends_on:
      - zookeeper
  
  kafka-wikistream:
    build: 
      context: services/kafkaWikiStream/
      dockerfile: Dockerfile.kafkaProducer
    image: kafka-wikistream
    container_name: kafka-wikistream
    networks:
      kafka-spark:
        ipv4_address: 172.28.0.7
    depends_on:
      - zookeeper
      - kafka
  # --------- Spark Services ---------
  spark-master:
    build:
      context: services/spark/
      dockerfile: Dockerfile.spark 
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no 
      - SPARK_SSL_ENABLED=no
    ports:
      - "8080:8080"
      - "7077:7077"
    networks:
      kafka-spark:
        ipv4_address: 172.28.0.8
    volumes:
      - ./sparkApps/:/opt/bitnami/spark/sparkApps/
      - ./tests/:/opt/bitnami/spark/tests
    depends_on:
      - kafka-wikistream
    links:
      - kafka

  spark-worker:
    build:
      context: services/spark/
      dockerfile: Dockerfile.spark
    container_name: spark-worker
    environment:
      - SPARK_MODE=worker 
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no 
      - SPARK_RPC_ENCRYPTION_ENABLED=no 
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - "8081:8081"
    networks:
      kafka-spark:
        ipv4_address: 172.28.0.9
    volumes:
      - ./sparkApps/:/opt/bitnami/spark/sparkApps/
      - ./tests/:/opt/bitnami/spark/tests
    depends_on:
      - spark-master
      - kafka-wikistream
    links:
      - kafka
    
  # --------- Spark Services ---------
  minio:
    image: minio/minio
    container_name: minio
    environment:
      - MINIO_ROOT_USER=testadmin
      - MINIO_ROOT_PASSWORD=testadminpwd
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      kafka-spark:
        ipv4_address: 172.28.0.10
    volumes:
      - ./storageWikiStream:/data
    command: server /data --console-address ":9001"
    restart: unless-stopped